-- Canonical schema setup moved to versioned migrations in /supabase/migrations.
-- Apply migrations in order instead of running ad-hoc DDL from this file.
--
-- Core requirements for the SaaS model:
-- 1) auth.users is the source of identity
-- 2) profiles.user_id references auth.users(id)
-- 3) business tables carry user_id uuid default auth.uid()
-- 4) RLS policies enforce user_id = auth.uid()
--
-- See:
-- - 001_base.sql
-- - 002_add_profile_id.sql
-- - 003_rls.sql
-- - 005_auth_user_scope.sql
